# Generated by Django 5.0.7 on 2024-09-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('ctype', models.CharField(max_length=20)),
                ('year', models.DateField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carbrand')),
            ],
        ),
    ]
